language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
matrix:
  allow_failures:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-rails.3.2.x
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: U/xpgxltcrxFKrV4w0q9PUHu7+WJow8v2hdP2oKYgU4ylfhAbnsmF6rFmzgZPtCt1N1jvO3qydpkSEqh27E4EJ1VDEr76jju3s4292LBBFtneqJx+Lnk4mCHE1NJo1Guyuug8sckP/I/JpDwqgtRgah+vYiley/LMQOVD12xIiQ=
